### ISSUE TITLE
[CT-2226] [Bug] ModuleNotFoundError `pytz` when doing a clean install of dbt-redshift v1.4.0

### ISSUE THREAD

**Issue by armandduijn** [dbt-labs/dbt-redshift#344]
### Is this a new bug in dbt-redshift?

- [X] I believe this is a new bug in dbt-redshift
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Running any CLI command in `dbt-redshift` v1.4.0 throws an exception. It's missing the `pytz` module.

### Expected Behavior

The CLI command runs without throwing an exception.

### Steps To Reproduce

1. Create a new virtual environment
2. Run `pip install dbt-redshift~=1.4`
3. Use the dbt CLI, e.g. `dbt deps`

### Relevant log output

```shell
(venv) PS C:\Users\[...]\dbt\projects\snowplow> dbt deps
Traceback (most recent call last):
  File "C:\Users\[...]\.pyenv\pyenv-win\versions\3.10.5\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\[...]\.pyenv\pyenv-win\versions\3.10.5\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\[...]\dbt\venv\Scripts\dbt.exe\__main__.py", line 4, in <module>
  File "C:\Users\[...]\dbt\venv\lib\site-packages\dbt\main.py", line 25, in <module>
    import dbt.task.build as build_task
  File "C:\Users\[...]\dbt\venv\lib\site-packages\dbt\task\build.py", line 1, in <module>
    from .run import RunTask, ModelRunner as run_model_runner
  File "C:\Users\[...]\dbt\venv\lib\site-packages\dbt\task\run.py", line 8, in <module>
    from .compile import CompileRunner, CompileTask
  File "C:\Users\[...]\dbt\venv\lib\site-packages\dbt\task\compile.py", line 4, in <module>
    from .runnable import GraphRunnableTask
  File "C:\Users\[...]\dbt\venv\lib\site-packages\dbt\task\runnable.py", line 11, in <module>
    from .printer import (
  File "C:\Users\[...]\dbt\venv\lib\site-packages\dbt\task\printer.py", line 22, in <module>
    from dbt.tracking import InvocationProcessor
  File "C:\Users\[...]\dbt\venv\lib\site-packages\dbt\tracking.py", line 26, in <module>
    import pytz
ModuleNotFoundError: No module named 'pytz'
```

### Environment

```markdown
- OS: Windows 10
- Python: 3.10
- dbt-core: 1.4.0 (I think?)
- dbt-redshift: 1.4.0
```

### Additional Context

I initially upgraded `dbt-redshift` from v1.1 to v1.4 and didn't experience any issues. I started getting the exception after I had deleted and recreated my virtual environment.

I'm also getting the same error in the GitHub Actions environment which uses Ubuntu 22.04 as the base image.

**Comment by armandduijn** [comment]
Separately running `pip install pytz` does resolve the problem but I don't think that's the most developer-friendly solution.

**Comment by jtcohen6** [comment]
Thanks for the report @armandduijn. I'm going to close this in favor of the same issue in `dbt-core`: https://github.com/dbt-labs/dbt-core/issues/7075
